# Generated by Django 4.1.7 on 2023-04-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Category',
            new_name='category',
        ),
    ]
